//-+--------------------------------------------------------------------
// Igatools a general purpose Isogeometric analysis library.
// Copyright (C) 2012-2015  by the igatools authors (see authors.txt).
//
// This file is part of the igatools library.
//
// The igatools library is free software: you can use it, redistribute
// it and/or modify it under the terms of the GNU General Public
// License as published by the Free Software Foundation, either
// version 3 of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//-+--------------------------------------------------------------------

#ifndef __OBJECTS_CONTAINER_READER_XML_SCHEMA_H_
#define __OBJECTS_CONTAINER_READER_XML_SCHEMA_H_

#include <igatools/base/config.h>

#ifdef XML_IO

#include <igatools/io/objects_container_xml_reader.h>

IGA_NAMESPACE_OPEN

const std::string ObjectsContainerXMLReader::IGATOOLS_FILE_FORMAT_VERSION = "1.0";

const std::string ObjectsContainerXMLReader::XML_SCHEMA_ =
"<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"
"<xs:schema attributeFormDefault=\"unqualified\"\n"
"           elementFormDefault=\"unqualified\"\n"
"           xmlns:xs=\"http://www.w3.org/2001/XMLSchema\">\n"
"\n"
"  <!-- ########################################################## -->\n"
"  <!-- Some basic general types definitions ##################### -->\n"
"  <!-- ########################################################## -->\n"
"\n"
"  <!-- Vector of doubles -->\n"
"  <xs:simpleType name=\"DoubleListType\">\n"
"    <xs:list itemType=\"xs:double\"/>\n"
"  </xs:simpleType>\n"
"\n"
"  <!-- Vector of non negative integers -->\n"
"  <xs:simpleType name=\"NonNegativeIntegerListType\">\n"
"    <xs:list itemType=\"xs:nonNegativeInteger\"/>\n"
"  </xs:simpleType>\n"
"\n"
"  <!-- Vector of booleans -->\n"
"  <xs:simpleType name=\"BooleanListType\">\n"
"    <xs:list itemType=\"xs:boolean\"/>\n"
"  </xs:simpleType>\n"
"\n"
"  <!-- Vector of doubles with minimum size 2 -->\n"
"  <xs:simpleType name=\"DoubleListMin2Type\">\n"
"    <xs:restriction base=\"DoubleListType\">\n"
"      <xs:minLength value=\"2\"/>\n"
"    </xs:restriction>\n"
"  </xs:simpleType>\n"
"\n"
"  <!-- Id type -->\n"
"  <xs:simpleType name=\"IdType\">\n"
"    <xs:restriction base=\"xs:nonNegativeInteger\"/>\n"
"  </xs:simpleType>\n"
"\n"
"  <!-- Size type -->\n"
"  <xs:simpleType name=\"SizeType\">\n"
"    <xs:restriction base=\"xs:nonNegativeInteger\"/>\n"
"  </xs:simpleType>\n"
"\n"
"  <!-- Vector of non negative integer with Size attribute -->\n"
"  <xs:complexType name=\"NonNegativeIntegerSizeListType\">\n"
"    <xs:simpleContent>\n"
"      <xs:extension base=\"NonNegativeIntegerListType\">\n"
"        <xs:attribute name=\"Size\" type=\"SizeType\" use=\"required\"/>\n"
"      </xs:extension>\n"
"    </xs:simpleContent>\n"
"  </xs:complexType>\n"
"\n"
"  <!-- Vector of non negative integer with Size and Direction attributes -->\n"
"  <xs:complexType name=\"NonNegativeIntegerSizeDirectionListType\">\n"
"    <xs:simpleContent>\n"
"      <xs:extension base=\"NonNegativeIntegerListType\">\n"
"        <xs:attribute name=\"Size\" type=\"SizeType\" use=\"required\"/>\n"
"        <xs:attribute name=\"Direction\" type=\"DirectionType\" use=\"required\"/>\n"
"      </xs:extension>\n"
"    </xs:simpleContent>\n"
"  </xs:complexType>\n"
"\n"
"  <!-- Vector of double with Size attribute -->\n"
"  <xs:complexType name=\"DoubleSizeListType\">\n"
"    <xs:simpleContent>\n"
"      <xs:extension base=\"DoubleListType\">\n"
"        <xs:attribute name=\"Size\" type=\"SizeType\" use=\"required\"/>\n"
"      </xs:extension>\n"
"    </xs:simpleContent>\n"
"  </xs:complexType>\n"
"\n"
"  <!-- Vector of double with Size and Direction attributes -->\n"
"  <xs:complexType name=\"DoubleSizeDirectionListType\">\n"
"    <xs:simpleContent>\n"
"      <xs:extension base=\"DoubleListType\">\n"
"        <xs:attribute name=\"Size\" type=\"SizeType\" use=\"required\"/>\n"
"        <xs:attribute name=\"Direction\" type=\"DirectionType\" use=\"required\"/>\n"
"      </xs:extension>\n"
"    </xs:simpleContent>\n"
"  </xs:complexType>\n"
"\n"
"  <!-- Vector of double with Size and Direction attributes and minimum size 2 -->\n"
"  <xs:complexType name=\"DoubleSizeDirectionListMin2Type\">\n"
"    <xs:simpleContent>\n"
"      <xs:extension base=\"DoubleListMin2Type\">\n"
"        <xs:attribute name=\"Size\" type=\"SizeType\" use=\"required\"/>\n"
"        <xs:attribute name=\"Direction\" type=\"DirectionType\" use=\"required\"/>\n"
"      </xs:extension>\n"
"    </xs:simpleContent>\n"
"  </xs:complexType>\n"
"\n"
"  <!-- ########################################################## -->\n"
"  <!-- Some base igatools types definitions ##################### -->\n"
"  <!-- ########################################################## -->\n"
"\n"
"  <!-- Direction type -->\n"
"  <xs:simpleType name=\"DirectionType\">\n"
"    <xs:restriction base=\"xs:nonNegativeInteger\">\n"
"      <!-- Igatools dimensions are limited here to 3 -->\n"
"      <xs:maxInclusive value=\"2\"/>\n"
"    </xs:restriction>\n"
"  </xs:simpleType>\n"
"\n"
"  <!-- Component type -->\n"
"  <xs:simpleType name=\"ComponentType\">\n"
"    <xs:restriction base=\"xs:nonNegativeInteger\">\n"
"      <!-- Igatools components are limited here to 3 -->\n"
"      <xs:maxInclusive value=\"2\"/>\n"
"    </xs:restriction>\n"
"  </xs:simpleType>\n"
"\n"
"  <!-- Type with ComponentId attribute -->\n"
"  <xs:complexType name=\"ComponentIdType\">\n"
"    <xs:attribute name=\"ComponentId\" type=\"ComponentType\" use=\"required\"/>\n"
"  </xs:complexType>\n"
"\n"
"  <!-- Dim type -->\n"
"  <xs:simpleType name=\"DimType\">\n"
"    <!-- Igatools dimensions are limited here to 3 -->\n"
"    <xs:restriction base=\"xs:nonNegativeInteger\">\n"
"      <xs:minInclusive value=\"0\"/>\n"
"      <xs:maxInclusive value=\"3\"/>\n"
"    </xs:restriction>\n"
"  </xs:simpleType>\n"
"\n"
"  <!-- Range type -->\n"
"  <xs:simpleType name=\"RangeType\">\n"
"    <!-- Igatools ranges are limited here to 3 -->\n"
"    <xs:restriction base=\"xs:positiveInteger\">\n"
"      <xs:minInclusive value=\"1\"/>\n"
"      <xs:maxInclusive value=\"3\"/>\n"
"    </xs:restriction>\n"
"  </xs:simpleType>\n"
"\n"
"  <!-- Rank type -->\n"
"  <xs:simpleType name=\"RankType\">\n"
"    <!-- Igatools ranks are limited here to 1 -->\n"
"    <xs:restriction base=\"xs:positiveInteger\">\n"
"      <xs:minInclusive value=\"1\"/>\n"
"      <xs:maxInclusive value=\"1\"/>\n"
"    </xs:restriction>\n"
"  </xs:simpleType>\n"
"\n"
"  <!-- Codim type -->\n"
"  <xs:simpleType name=\"CodimType\">\n"
"    <!-- Igatools codims are limited here to 2 -->\n"
"    <xs:restriction base=\"xs:nonNegativeInteger\">\n"
"      <xs:minInclusive value=\"0\"/>\n"
"      <xs:maxInclusive value=\"2\"/>\n"
"    </xs:restriction>\n"
"  </xs:simpleType>\n"
"\n"
"  <!-- Spacedim type -->\n"
"  <xs:simpleType name=\"SpacedimType\">\n"
"    <!-- Igatools spaceims are limited here to 3 -->\n"
"    <xs:restriction base=\"xs:nonNegativeInteger\">\n"
"      <xs:minInclusive value=\"0\"/>\n"
"      <xs:maxInclusive value=\"3\"/>\n"
"    </xs:restriction>\n"
"  </xs:simpleType>\n"
"\n"
"  <!-- Transformation type: h_grad, h_curl, h_div and l2 -->\n"
"  <xs:simpleType name=\"TransformationType\">\n"
"    <xs:restriction base=\"xs:normalizedString\">\n"
"      <xs:enumeration value=\"h_grad\"/>\n"
"      <xs:enumeration value=\"h_curl\"/>\n"
"      <xs:enumeration value=\"h_div\"/>\n"
"      <xs:enumeration value=\"l_2\"/>\n"
"    </xs:restriction>\n"
"  </xs:simpleType>\n"
"\n"
"  <!-- End behaviour type: interpolatory, end_knots or periodic -->\n"
"  <xs:simpleType name=\"EndBehaviourType\">\n"
"    <xs:restriction base=\"xs:normalizedString\">\n"
"      <xs:enumeration value=\"interpolatory\"/>\n"
"      <xs:enumeration value=\"end_knots\"/>\n"
"      <xs:enumeration value=\"periodic\"/>\n"
"    </xs:restriction>\n"
"  </xs:simpleType>\n"
"\n"
"  <!-- Vector of end behaviour types -->\n"
"  <xs:simpleType name=\"EndBehaviourListType\">\n"
"    <xs:list itemType=\"EndBehaviourType\"/>\n"
"  </xs:simpleType>\n"
"\n"
"  <!-- Type with LocalObjectId attribute -->\n"
"  <xs:complexType name=\"LocalObjectIdType\">\n"
"    <xs:attribute name=\"LocalObjectId\" type=\"IdType\" use=\"required\"/>\n"
"  </xs:complexType>\n"
"\n"
"  <!-- Type with LocalObjectId and Dim attributes -->\n"
"  <xs:complexType name=\"LocalObjectIdDimType\">\n"
"    <xs:complexContent>\n"
"      <xs:extension base=\"LocalObjectIdType\">\n"
"        <xs:attribute name=\"Dim\" type=\"DimType\" use=\"required\"/>\n"
"      </xs:extension>\n"
"    </xs:complexContent>\n"
"  </xs:complexType>\n"
"\n"
"  <!-- Type with LocalObjectId, Dim, Range and Rank attributes -->\n"
"  <xs:complexType name=\"LocalObjectIdDimRangeRankType\">\n"
"    <xs:complexContent>\n"
"      <xs:extension base=\"LocalObjectIdDimType\">\n"
"        <xs:attribute name=\"Range\" type=\"RangeType\" use=\"required\"/>\n"
"        <xs:attribute name=\"Rank\" type=\"RankType\" use=\"required\"/>\n"
"      </xs:extension>\n"
"    </xs:complexContent>\n"
"  </xs:complexType>\n"
"\n"
"  <!-- Type with LocalObjectId, Dim, Range, Rank and Codim attributes -->\n"
"  <xs:complexType name=\"LocalObjectIdDimRangeRankCodimType\">\n"
"    <xs:complexContent>\n"
"      <xs:extension base=\"LocalObjectIdDimRangeRankType\">\n"
"        <xs:attribute name=\"Codim\" type=\"CodimType\" use=\"required\"/>\n"
"      </xs:extension>\n"
"    </xs:complexContent>\n"
"  </xs:complexType>\n"
"\n"
"  <!-- Type with LocalObjectId, Dim and Codim attributes -->\n"
"  <xs:complexType name=\"LocalObjectIdDimCodimType\">\n"
"    <xs:complexContent>\n"
"      <xs:extension base=\"LocalObjectIdDimType\">\n"
"        <xs:attribute name=\"Codim\" type=\"CodimType\" use=\"required\"/>\n"
"      </xs:extension>\n"
"    </xs:complexContent>\n"
"  </xs:complexType>\n"
"\n"
"  <!-- Type with LocalObjectId, Dim, Codim and Range attributes -->\n"
"  <xs:complexType name=\"LocalObjectIdDimCodimRangeType\">\n"
"    <xs:complexContent>\n"
"      <xs:extension base=\"LocalObjectIdDimCodimType\">\n"
"        <xs:attribute name=\"Range\" type=\"RangeType\" use=\"required\"/>\n"
"      </xs:extension>\n"
"    </xs:complexContent>\n"
"  </xs:complexType>\n"
"\n"
"  <!-- Type with LocalObjectId, Dim and Spacedim attributes -->\n"
"  <xs:complexType name=\"LocalObjectIdDimSpacedimType\">\n"
"    <xs:complexContent>\n"
"      <xs:extension base=\"LocalObjectIdDimType\">\n"
"        <xs:attribute name=\"Spacedim\" type=\"SpacedimType\" use=\"required\"/>\n"
"      </xs:extension>\n"
"    </xs:complexContent>\n"
"  </xs:complexType>\n"
"\n"
"  <!-- Type with GetFromLocalObjectId attribute -->\n"
"  <xs:complexType name=\"GetFromLocalObjectIdType\">\n"
"    <xs:attribute name=\"GetFromLocalObjectId\" type=\"IdType\" use=\"required\"/>\n"
"  </xs:complexType>\n"
"\n"
"\n"
"\n"
"  <!-- ########################################################## -->\n"
"  <!-- Main igatools types definitions ########################## -->\n"
"  <!-- ########################################################## -->\n"
"\n"
"  <!-- Grid type -->\n"
"  <xs:complexType name=\"GridType\">\n"
"    <xs:complexContent>\n"
"      <xs:extension base=\"LocalObjectIdDimType\">\n"
"        <xs:all>\n"
"          <xs:element name=\"Knots\" minOccurs=\"1\" maxOccurs=\"1\">\n"
"            <xs:complexType>\n"
"              <xs:sequence>\n"
"                <xs:element name=\"Knots\" minOccurs=\"0\" maxOccurs=\"3\" type=\"DoubleSizeDirectionListMin2Type\"/>\n"
"              </xs:sequence>\n"
"            </xs:complexType>\n"
"          </xs:element>\n"
"          <!-- Note that this tag is optional -->\n"
"          <xs:element name=\"Name\" type=\"xs:normalizedString\" minOccurs=\"0\" maxOccurs=\"1\"/>\n"
"        </xs:all>\n"
"      </xs:extension>\n"
"    </xs:complexContent>\n"
"  </xs:complexType>\n"
"\n"
"  <!-- SplineSpace type -->\n"
"  <xs:complexType name=\"SplineSpaceType\">\n"
"    <xs:complexContent>\n"
"      <xs:extension base=\"LocalObjectIdDimRangeRankType\">\n"
"        <xs:all>\n"
"\n"
"          <xs:element name=\"Grid\" type=\"GetFromLocalObjectIdType\"/>\n"
"\n"
"          <xs:element name=\"SplineSpaceComponents\">\n"
"            <xs:complexType>\n"
"              <xs:sequence>\n"
"                <xs:element name=\"SplineSpaceComponent\" minOccurs=\"0\" maxOccurs=\"3\">\n"
"                  <xs:complexType>\n"
"                    <xs:complexContent>\n"
"                      <xs:extension base=\"ComponentIdType\">\n"
"                        <xs:all>\n"
"\n"
"                          <xs:element name=\"Degrees\" type=\"NonNegativeIntegerListType\"/>\n"
"\n"
"                          <xs:element name=\"InteriorMultiplicities\">\n"
"                            <xs:complexType>\n"
"                              <xs:sequence>\n"
"                                <xs:element name=\"InteriorMultiplicities\" minOccurs=\"0\" maxOccurs=\"3\" type=\"NonNegativeIntegerSizeDirectionListType\"/>\n"
"                              </xs:sequence>\n"
"                            </xs:complexType>\n"
"                          </xs:element>\n"
"\n"
"                          <!-- Note that this tag is optional -->\n"
"                          <xs:element name=\"Periodicity\" type=\"BooleanListType\" minOccurs=\"0\" maxOccurs=\"1\"/>\n"
"\n"
"                        </xs:all>\n"
"                      </xs:extension>\n"
"                    </xs:complexContent>\n"
"                  </xs:complexType>\n"
"                </xs:element>\n"
"              </xs:sequence>\n"
"            </xs:complexType>\n"
"          </xs:element>\n"
"\n"
"        </xs:all>\n"
"      </xs:extension>\n"
"    </xs:complexContent>\n"
"  </xs:complexType>\n"
"\n"
"  <!-- BSpline type -->\n"
"  <xs:complexType name=\"BSplineType\">\n"
"    <xs:complexContent>\n"
"      <xs:extension base=\"LocalObjectIdDimRangeRankType\">\n"
"        <xs:all>\n"
"\n"
"          <xs:element name=\"SplineSpace\" type=\"GetFromLocalObjectIdType\"/>\n"
"\n"
"          <!-- Note that this tag is optional -->\n"
"          <xs:element name=\"EndBehaviour\" minOccurs=\"0\" maxOccurs=\"1\">\n"
"            <xs:complexType>\n"
"              <xs:sequence>\n"
"                <xs:element name=\"EndBehaviour\" minOccurs=\"0\" maxOccurs=\"3\">\n"
"                  <xs:complexType>\n"
"                    <xs:simpleContent>\n"
"                      <xs:extension base=\"EndBehaviourListType\">\n"
"                        <xs:attribute name=\"ComponentId\" type=\"IdType\" use=\"required\"/>\n"
"                      </xs:extension>\n"
"                    </xs:simpleContent>\n"
"                  </xs:complexType>\n"
"                </xs:element>\n"
"              </xs:sequence>\n"
"            </xs:complexType>\n"
"          </xs:element>\n"
"\n"
"        </xs:all>\n"
"      </xs:extension>\n"
"    </xs:complexContent>\n"
"  </xs:complexType>\n"
"\n"
"  <!-- IdentityGridFunction type -->\n"
"  <xs:complexType name=\"IdentityGridFunctionType\">\n"
"    <xs:complexContent>\n"
"      <xs:extension base=\"LocalObjectIdDimType\">\n"
"        <xs:all>\n"
"          <xs:element name=\"Grid\" type=\"GetFromLocalObjectIdType\"/>\n"
"          <!-- Note that this tag is optional -->\n"
"          <xs:element name=\"Name\" type=\"xs:normalizedString\" minOccurs=\"0\" maxOccurs=\"1\"/>\n"
"        </xs:all>\n"
"      </xs:extension>\n"
"    </xs:complexContent>\n"
"  </xs:complexType>\n"
"\n"
"  <!-- ConstantGridFunction type -->\n"
"  <xs:complexType name=\"ConstantGridFunctionType\">\n"
"    <xs:complexContent>\n"
"      <xs:extension base=\"LocalObjectIdDimSpacedimType\">\n"
"        <xs:all>\n"
"          <xs:element name=\"Grid\" type=\"GetFromLocalObjectIdType\"/>\n"
"          <xs:element name=\"Values\" type=\"DoubleListType\"/>\n"
"          <!-- Note that this tag is optional -->\n"
"          <xs:element name=\"Name\" type=\"xs:normalizedString\" minOccurs=\"0\" maxOccurs=\"1\"/>\n"
"        </xs:all>\n"
"      </xs:extension>\n"
"    </xs:complexContent>\n"
"  </xs:complexType>\n"
"\n"
"  <!-- LinearGridFunction type -->\n"
"  <xs:complexType name=\"LinearGridFunctionType\">\n"
"    <xs:complexContent>\n"
"      <xs:extension base=\"LocalObjectIdDimSpacedimType\">\n"
"        <xs:all>\n"
"          <xs:element name=\"Grid\" type=\"GetFromLocalObjectIdType\"/>\n"
"          <xs:element name=\"A\" type=\"DoubleListType\"/>\n"
"          <xs:element name=\"b\" type=\"DoubleListType\"/>\n"
"          <!-- Note that this tag is optional -->\n"
"          <xs:element name=\"Name\" type=\"xs:normalizedString\" minOccurs=\"0\" maxOccurs=\"1\"/>\n"
"        </xs:all>\n"
"      </xs:extension>\n"
"    </xs:complexContent>\n"
"  </xs:complexType>\n"
"\n"
"  <!-- IgCoefficients type -->\n"
"  <xs:complexType name=\"IgCoefficientsType\">\n"
"    <xs:all>\n"
"      <xs:element name=\"Indices\" type=\"NonNegativeIntegerListType\"/>\n"
"      <xs:element name=\"Values\"  type=\"DoubleListType\"/>\n"
"    </xs:all>\n"
"    <xs:attribute name=\"Size\" type=\"SizeType\" use=\"required\"/>\n"
"  </xs:complexType>\n"
"\n"
"  <!-- IgGridFunction type -->\n"
"  <xs:complexType name=\"IgGridFunctionType\">\n"
"    <xs:complexContent>\n"
"      <xs:extension base=\"LocalObjectIdDimSpacedimType\">\n"
"        <xs:all>\n"
"          <xs:element name=\"ReferenceSpaceBasis\" type=\"GetFromLocalObjectIdType\"/>\n"
"          <xs:element name=\"IgCoefficients\" type=\"IgCoefficientsType\"/>\n"
"          <!-- Note that this tag is optional -->\n"
"          <xs:element name=\"Name\" type=\"xs:normalizedString\" minOccurs=\"0\" maxOccurs=\"1\"/>\n"
"          <!-- Note that this tag is optional -->\n"
"          <xs:element name=\"DofsProperty\" type=\"xs:normalizedString\" minOccurs=\"0\" maxOccurs=\"1\"/>\n"
"        </xs:all>\n"
"      </xs:extension>\n"
"    </xs:complexContent>\n"
"  </xs:complexType>\n"
"\n"
"  <!-- NURBS type -->\n"
"  <xs:complexType name=\"NURBSType\">\n"
"    <xs:complexContent>\n"
"      <xs:extension base=\"LocalObjectIdDimRangeRankType\">\n"
"        <xs:all>\n"
"          <xs:element name=\"BSpline\" type=\"GetFromLocalObjectIdType\"/>\n"
"          <xs:element name=\"WeightFunction\" type=\"GetFromLocalObjectIdType\"/>\n"
"        </xs:all>\n"
"      </xs:extension>\n"
"    </xs:complexContent>\n"
"  </xs:complexType>\n"
"\n"
"  <!-- Domain type -->\n"
"  <xs:complexType name=\"DomainType\">\n"
"    <xs:complexContent>\n"
"      <xs:extension base=\"LocalObjectIdDimCodimType\">\n"
"        <xs:all>\n"
"          <xs:element name=\"GridFunction\" type=\"GetFromLocalObjectIdType\"/>\n"
"          <!-- Note that this tag is optional -->\n"
"          <xs:element name=\"Name\" type=\"xs:normalizedString\" minOccurs=\"0\" maxOccurs=\"1\"/>\n"
"        </xs:all>\n"
"      </xs:extension>\n"
"    </xs:complexContent>\n"
"  </xs:complexType>\n"
"\n"
"  <!-- PhysicalSpaceBasis type -->\n"
"  <xs:complexType name=\"PhysicalSpaceBasisType\">\n"
"    <xs:complexContent>\n"
"      <xs:extension base=\"LocalObjectIdDimRangeRankCodimType\">\n"
"        <xs:all>\n"
"          <xs:element name=\"ReferenceSpaceBasis\" type=\"GetFromLocalObjectIdType\"/>\n"
"          <xs:element name=\"Domain\" type=\"GetFromLocalObjectIdType\"/>\n"
"          <!-- Note that this tag is optional -->\n"
"          <xs:element name=\"Transformation\" type=\"TransformationType\" minOccurs=\"0\" maxOccurs=\"1\"/>\n"
"        </xs:all>\n"
"      </xs:extension>\n"
"    </xs:complexContent>\n"
"  </xs:complexType>\n"
"\n"
"  <!-- IgFunction type -->\n"
"  <xs:complexType name=\"IgFunctionType\">\n"
"    <xs:complexContent>\n"
"      <xs:extension base=\"LocalObjectIdDimRangeRankCodimType\">\n"
"        <xs:all>\n"
"          <xs:element name=\"PhysicalSpaceBasis\" type=\"GetFromLocalObjectIdType\"/>\n"
"          <xs:element name=\"IgCoefficients\" type=\"IgCoefficientsType\"/>\n"
"          <!-- Note that this tag is optional -->\n"
"          <xs:element name=\"Name\" type=\"xs:normalizedString\" minOccurs=\"0\" maxOccurs=\"1\"/>\n"
"          <!-- Note that this tag is optional -->\n"
"          <xs:element name=\"DofsProperty\" type=\"xs:normalizedString\" minOccurs=\"0\" maxOccurs=\"1\"/>\n"
"        </xs:all>\n"
"      </xs:extension>\n"
"    </xs:complexContent>\n"
"  </xs:complexType>\n"
"\n"
"  <!-- ConstantFunction type -->\n"
"  <xs:complexType name=\"ConstantFunctionType\">\n"
"    <xs:complexContent>\n"
"      <xs:extension base=\"LocalObjectIdDimRangeRankCodimType\">\n"
"        <xs:all>\n"
"          <xs:element name=\"Domain\" type=\"GetFromLocalObjectIdType\"/>\n"
"          <xs:element name=\"Values\" type=\"DoubleListType\"/>\n"
"        </xs:all>\n"
"      </xs:extension>\n"
"    </xs:complexContent>\n"
"  </xs:complexType>\n"
"\n"
"  <!-- LinearFunction type -->\n"
"  <xs:complexType name=\"LinearFunctionType\">\n"
"    <xs:complexContent>\n"
"      <xs:extension base=\"LocalObjectIdDimCodimRangeType\">\n"
"        <xs:all>\n"
"          <xs:element name=\"Domain\" type=\"GetFromLocalObjectIdType\"/>\n"
"          <xs:element name=\"A\" type=\"DoubleListType\"/>\n"
"          <xs:element name=\"b\" type=\"DoubleListType\"/>\n"
"        </xs:all>\n"
"      </xs:extension>\n"
"    </xs:complexContent>\n"
"  </xs:complexType>\n"
"\n"
"  <!-- Main igatools XML element type -->\n"
"  <xs:element name=\"Igatools\">\n"
"    <xs:complexType>\n"
"      <xs:sequence>\n"
"        <xs:choice maxOccurs=\"unbounded\">\n"
"          <xs:element name=\"Grid\" type=\"GridType\"/>\n"
"          <xs:element name=\"SplineSpace\" type=\"SplineSpaceType\"/>\n"
"          <xs:element name=\"BSpline\" type=\"BSplineType\"/>\n"
"          <xs:element name=\"IdentityGridFunction\" type=\"IdentityGridFunctionType\"/>\n"
"          <xs:element name=\"ConstantGridFunction\" type=\"ConstantGridFunctionType\"/>\n"
"          <xs:element name=\"LinearGridFunction\" type=\"LinearGridFunctionType\"/>\n"
"          <xs:element name=\"IgGridFunction\" type=\"IgGridFunctionType\"/>\n"
"          <xs:element name=\"NURBS\" type=\"NURBSType\"/>\n"
"          <xs:element name=\"Domain\" type=\"DomainType\"/>\n"
"          <xs:element name=\"PhysicalSpaceBasis\" type=\"PhysicalSpaceBasisType\"/>\n"
"          <xs:element name=\"IgFunction\" type=\"IgFunctionType\"/>\n"
"          <xs:element name=\"ConstantFunction\" type=\"ConstantFunctionType\"/>\n"
"          <xs:element name=\"LinearFunction\" type=\"LinearFunctionType\"/>\n"
"        </xs:choice>\n"
"      </xs:sequence>\n"
"      <xs:attribute name=\"FormatVersion\" type=\"xs:float\" fixed=\"" +
IGATOOLS_FILE_FORMAT_VERSION + "\" use=\"required\"/>\n"
"    </xs:complexType>\n"
"  </xs:element>\n"
"\n"
"</xs:schema>\n";

IGA_NAMESPACE_CLOSE

#endif // XML_IO

#endif // __OBJECTS_CONTAINER_READER_XML_SCHEMA_H_
