#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# Print important information at the end of cmake configure
#-------------------------------------------------------------------------------
macro(print_final_message)
  message("")
  message("")
  message("******************************************************************")
  message("**")
  message("** [1] To compile and install the library run: ")
  message("** \t make install")
  message("**")
  message("** [2] To use the library it should be made visible to the loader.")
  if(APPLE)
    message("**     Add the following line to your ~/.bash_login")
    message("** \t export DYLD_LIBRARY_PATH=\\")
    message("** \t  $DYLD_LIBRARY_PATH:${CMAKE_INSTALL_PREFIX}/lib")
  else(APPLE)
    if(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
      message("**     Add the following line to your ~/.bash_rc")
      message("** \t export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${CMAKE_INSTALL_PREFIX}/lib")
      #    message("** \t  $LD_LIBRARY_PATH:${CMAKE_INSTALL_PREFIX}/lib")   
    endif(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
  endif(APPLE)
  message("**")
  message("** [3] To generate and install the online documentation run: ")
  message("** \t make doc")
  message("**")
  message("******************************************************************")
  message("")
  message("")
endmacro(print_final_message)