//-+--------------------------------------------------------------------
// Igatools a general purpose Isogeometric analysis library.
// Copyright (C) 2012-2015  by the igatools authors (see authors.txt).
//
// This file is part of the igatools library.
//
// The igatools library is free software: you can use it, redistribute
// it and/or modify it under the terms of the GNU General Public
// License as published by the Free Software Foundation, either
// version 3 of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//-+--------------------------------------------------------------------

#ifndef VALUE_TYPES_H_
#define VALUE_TYPES_H_

#include <igatools/base/config.h>

#include <boost/mpl/map.hpp>
#include <boost/mpl/int.hpp>


#include <string>

IGA_NAMESPACE_OPEN


template <int value_type_id>
class ValueType;

// TODO (pauletti, Apr 10, 2015): this is NOT dimension independent code!!!
// it's adding code withou benefit, simpler define constexpr Hessian=2?
// Moreover we were going to use get_elem_hessian, generated by cog for ex
template<>
class ValueType<0>
{
public:
    static constexpr int id = 0;
    static constexpr int order = 0;
    static const std::string name;
    static const auto flag = ValueFlags::value;
};
using _Value = ValueType<0>;


template<>
class ValueType<1>
{
public:
    static constexpr int id = 1;
    static constexpr int order = 1;
    static const std::string name;
    static const auto flag = ValueFlags::gradient;
};
using _Gradient = ValueType<1>;


template<>
class ValueType<2>
{
public:
    static constexpr int id = 2;
    static constexpr int order = 2;
    static const std::string name;
    static const auto flag = ValueFlags::hessian;
};
using _Hessian = ValueType<2>;


template<>
class ValueType<-1>
{
public:
    static constexpr int id = -1;
    static constexpr int order = 1;
    static const std::string name;
    static const auto flag = ValueFlags::divergence;
};
using _Divergence = ValueType<-1>;


template<>
class ValueType<-3>
{
public:
    static constexpr int id = -3;
    static constexpr int order = 0;
    static const std::string name;
    static const auto flag = ValueFlags::point;
};
using _Point = ValueType<-3>;


template<>
class ValueType<-4>
{
public:
    static constexpr int id = -4;
    static constexpr int order = 0;
    static const std::string name;
    static const auto flag = ValueFlags::w_measure;
};
using _W_Measure = ValueType<-4>;


template<>
class ValueType<-5>
{
public:
    static constexpr int id = -5;
    static constexpr int order = 0;
    static const std::string name;
    static const auto flag = ValueFlags::measure;
};
using _Measure = ValueType<-5>;


template<>
class ValueType<-6>
{
public:
    static constexpr int id = -6;
    static constexpr int order = 1;
    static const std::string name;
    static const auto flag = ValueFlags::inv_gradient;
};
using _InvGradient = ValueType<-6>;


template<>
class ValueType<-7>
{
public:
    static constexpr int id = -7;
    static constexpr int order = 1;
    static const std::string name;
    static const auto flag = ValueFlags::inv_hessian;
};
using _InvHessian = ValueType<-7>;

IGA_NAMESPACE_CLOSE

#endif //#ifndef  VALUE_TYPES_H_
