//-+--------------------------------------------------------------------
// Igatools a general purpose Isogeometric analysis library.
// Copyright (C) 2012-2015  by the igatools authors (see authors.txt).
//
// This file is part of the igatools library.
//
// The igatools library is free software: you can use it, redistribute
// it and/or modify it under the terms of the GNU General Public
// License as published by the Free Software Foundation, either
// version 3 of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//-+--------------------------------------------------------------------

#ifndef VALUE_TYPES_H_
#define VALUE_TYPES_H_

#include <igatools/base/config.h>

#include <boost/mpl/map.hpp>
#include <boost/mpl/int.hpp>


#include <string>

IGA_NAMESPACE_OPEN


template <int value_type_id>
class ValueType;

// TODO (pauletti, Apr 10, 2015): this is NOT dimension independent code!!!
// it's adding code withou benefit, simpler define constexpr Hessian=2?
// Moreover we were going to use get_elem_hessian, generated by cog for ex
template<>
class ValueType<0>
{
public:
    static constexpr int id = 0;
    static constexpr int order = 0;
    static const std::string name;
};
using _Value = ValueType<0>;


template<>
class ValueType<1>
{
public:
    static constexpr int id = 1;
    static constexpr int order = 1;
    static const std::string name;
};
using _Gradient = ValueType<1>;

template<>
class ValueType<2>
{
public:
    static constexpr int id = 2;
    static constexpr int order = 2;
    static const std::string name;
};
using _Hessian = ValueType<2>;


template<>
class ValueType<-1>
{
public:
    static constexpr int id = -1;
    static constexpr int order = 1;
    static const std::string name;
};
using _Divergence = ValueType<-1>;




using map_ValueType_TuplePosition = boost::mpl::map<
                                    boost::mpl::pair<     _Value,boost::mpl::int_<0> >,
                                    boost::mpl::pair<  _Gradient,boost::mpl::int_<1> >,
                                    boost::mpl::pair<   _Hessian,boost::mpl::int_<2> >,
                                    boost::mpl::pair<_Divergence,boost::mpl::int_<3> >
                                    >;
using map_VT_TP = map_ValueType_TuplePosition;

template <class ValueType>
using TuplePosition_from_ValueType = typename boost::mpl::at<map_VT_TP,ValueType>::type;


IGA_NAMESPACE_CLOSE

#endif //#ifndef  VALUE_TYPES_H_
